title: Hope Tsai # your name (or website title) here
logo: "/images/IMG_2028.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I am a junior at Amherst College, double majoring in mathematics and computer science, which shocks my younger self.
  <br><br>
  When I was younger, I planned on studying English; I loved how simple letters and punctuation, strung together, could impact me so much, and I wanted to share that with the rest of the world.
  However, I soon realized that I am easily influenced by the content I consume, and that reading heavy literature all the time would not be the best for me.
  Moreover, as a low-income student, I learned that I place greater priority on solving practical problems.
  How could someone enjoy a good book if they are too busy, living paycheck to paycheck?
  All of this led me to computer science, which allows me to create something practically impactful out of simple letters and punctuation. 
  Math, on the other hand, gives me the beauty and stories (each problem and proof is a beautiful story!) of English, while keeping me emotionally grounded.
  However, I still love the humanities, and balance my courseload accordingly! I hope to be a bridge between the humanities and STEM, both in college and beyond.
  
  <br><br>
  <a href="https://www.linkedin.com/in/hope-tsai-341853145/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
