title: Hope Tsai # your name (or website title) here
logo: "/images/IMG_2028.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I am a junior at Amherst College, double majoring in mathematics and computer science.
  <br><br>
  Though I had planned on studying English, I realized that I love, and need, the groundedness of these two subjects.
  Just as in English, my initial major, I see the beauty and storytelling in every mathematical problem.
  In computer science, I see the impact of a good solution to a practical problem; 
  though the impact of a good story is undoubtedly important, I, as a low-income student, place greater priority on solving practical problems.
  However, I still love the humanities, and balance my courseload accordingly! I hope to be a bridge between the humanities and STEM, both in college and beyond.
  
  <br><br>
  <a href="https://www.linkedin.com/in/hope-tsai-341853145/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
